/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        gainsboro: "#dddee2",
        black: "#000",
        "blue-primary": "#4daeff",
        "light-black": "#313945",
        "icons-color-02": "#d7d9e6",
        whitesmoke: "#f6fafc",
        "dark-blue": "#0153c9",
        gray: {
          "100": "#feffff",
          "200": "#7b7b7e",
          "300": "rgba(255, 255, 255, 0.01)",
        },
        lightsteelblue: "#c6cef0",
        darkgray: "#a7a7a7",
        palegoldenrod: "#ffedb2",
        goldenrod: "#db9f15",
        aliceblue: "#ebedf5",
        "text-ffffff": "#fff",
        moccasin: "#ffefba",
        buy: "#fc6b21",
        "text-3-": "#86909c",
        transfer: "#1fb9fc",
        "text-5-": "#1d2129",
        antiquewhite: "#ffe9db",
        lavender: {
          "100": "#eceafe",
          "200": "#e3e0ff",
        },
        sell: "#5531fb",
        honeydew: "#efffec",
        darkturquoise: {
          "100": "#0fc6c2",
          "200": "#11bdbe",
        },
        "brand1-6-": "#165dff",
        "ui-color-ui-gray": "#808080",
        "label-colors-lc-l-secondary": "rgba(60, 60, 67, 0.6)",
        "cards-bg": "#fefeff",
        salmon: "#f9896b",
      },
      fontFamily: {
        lato: "Lato",
        "default-size-callout": "'SF Pro Text'",
        "large-default-footnote": "Roboto",
        poppins: "Poppins",
        nunito: "Nunito",
      },
      borderRadius: {
        "11xl": "30px",
        "10xs-1": "2.1px",
        "2xs-9": "10.9px",
        "81xl": "100px",
        "3xs": "10px",
        "6xs": "7px",
      },
    },
    fontSize: {
      mid: "17px",
      lg: "18px",
      sm: "14px",
      base: "16px",
      xl: "20px",
      xs: "12px",
      "5xs": "8px",
      smi: "13px",
      "3xs": "10px",
    },
  },
  corePlugins: {
    preflight: false,
  },
};
